name: analytics_repository
description: A Dart package which manages analytics business rules.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  local_analytics_api:
    path: ../local_analytics_api

dev_dependencies:
  mocktail: ^0.1.4
  test: ^1.17.0
  very_good_analysis: ^2.4.0
