name: shared_preferences_repository
description: A Dart package which manages local storage using shared_preferences.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  preferences_repository:
    path: ../preferences_repository
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
