name: profile
description: Dart package with models for a profile account.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
