name: hive_preferences_repository
description: A Dart package which manages local storage using Hive.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive: ^2.2.3
  preferences_repository:
    path: ../preferences_repository

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
