name: preferences_repository
description: A Dart package which defines business rules for local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
