name: search_filter_api
description: Search filter API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  hive: ^2.0.4
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.0
  json_serializable: ^5.0.0
  mocktail: ^0.1.4
  test: ^1.17.0
  very_good_analysis: ^2.3.0
