name: launch_analytics
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.5"

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_services_binding: ^0.1.0
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.2
  local_analytics_api:
    path: packages/local_analytics_api
  path_provider: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
