name: local_analytics_api
description: A Dart package which manages local storage interactions for analytics.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  hive: ^2.0.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^3.0.0
