name: local_analytics_api
description: A Dart package which manages local storage interactions for analytics.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive: ^2.2.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
