name: form_flow
description: A Flutter project that handles form submission with flow_builder and bloc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.3"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz_inputs:
    path: packages/formz_inputs
  intl: ^0.18.0
  profile:
    path: packages/profile

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
