name: mentoring
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_analytics_api:
    path: packages/local_analytics_api
  analytics_repository:
    path: packages/analytics_repository
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  hive_flutter: ^1.1.0
  hydrated_bloc: ^7.0.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
