name: preference_navigation
description: A Flutter project to show how to start an app based on a state.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.5"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_preferences_repository:
    path: packages/preferences_repository/hive_preferences_repository
  path_provider: ^2.0.15
  preferences_repository:
    path: packages/preferences_repository/preferences_repository
  shared_preferences: ^2.2.0
  shared_preferences_repository:
    path: packages/preferences_repository/shared_preferences_repository

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
