name: preference_navigation
description: A Flutter project to show how to start an app based on a state.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: "3.3.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  # https://github.com/flutter/flutter/issues/94123
  flutter_services_binding: ^0.1.0
  hive: ^2.0.4
  hive_preferences_repository:
    path: packages/preferences_repository/hive_preferences_repository
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  shared_preferences_repository:
    path: packages/preferences_repository/shared_preferences_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
