name: examples

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: "Install Tools"
        run: |
          flutter pub global activate melos

      - name: Initialize melos and get dependencies
        run: melos bs && melos run pub-get

      - name: Run tests
        run: melos run test:all