name: examples

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.7.0-3.1.pre
          channel: "beta"

      - name: Install Tools
        run: |
          flutter pub global activate melos

      - name: Initialize tools
        run: melos bs

      - name: Run CI workflow (format, analyze, test)
        run: melos run WF:ci

      - name: Check 95% code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "./coverage/merged.lcov.info"
          min_coverage: 95
          exclude: "**/*.freezed.dart **/*.g.dart **/*.gr.dart"

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: "./coverage/merged.lcov.info"
          fail_ci_if_error: true
          verbose: true
