name: preference_navigation

on:
  push:
    paths:
      - ".github/workflows/preference_navigation.yaml"
      - "examples/preference_navigation/**"

  pull_request:
    paths:
      - ".github/workflows/preference_navigation.yaml"
      - "examples/preference_navigation/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: "stable"
      flutter_version: "3.10.5"
      working_directory: "examples/preference_navigation"
